language: cpp

git:
  depth: 10

# sudo:required is needed for trusty images
sudo: required
dist: bionic

# https://blog.travis-ci.com/2017-12-12-new-trusty-images-q4-launch
# group: deprecated-2017Q4

notifications:
  email: false

branches:
  only:
    - master
    - dev

stages:
  - test

env:
  global:
    - JOBS=8

jobs:

  # We override the compiler names here to yield better ccache behavior, which uses this as key
  include:

    - &linux-test
      name: Tests / Linux / gcc7 / Debug
      stage: test
      os: linux
      language: cpp
      compiler: "gcc-7-debug"
      addons: &gcc6
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: [
            'python3-pip', 
            'g++-7',
            'librocksdb-dev',
            'libglib2.0-dev',
            'libboost-system-dev',
            'libboost-filesystem-dev',
            'libboost-program-options-dev',
            'libboost-python-dev',
            'python3-setuptools',
            'python3-dev',
            'python3-pip',
            'python3',
            'make',
            'cmake',
            'antlr',
            'llvm',
            'libcurl4-openssl-dev',
            'libclang-dev'
            ]
      env: CCOMPILER='gcc-7' CXXCOMPILER='g++-7' BUILD_TYPE='Debug'

      install: scripts/travis/install-tests.sh
      script: scripts/travis/run-tests.sh

    - <<: *linux-test
      name: Tests / Linux / gcc7 / Release
      compiler: "gcc-7-release"
      env: CCOMPILER='gcc-7' CXXCOMPILER='g++-7' BUILD_TYPE='Release'
    