site_name: sc-machine

extra_css:
  - _assets/main.css
extra_javascript:
  - _assets/scg.min.js
  - _assets/main.js

nav:
  - Home: index.md
  - Installation with Docker: docker.md
  - Build:
      - Build on Linux: build/linux_build.md
      - Build on OSX: build/osx_build.md
      - CMake flags: build/cmake_flags.md
      - Configuration file: build/config.md
  - API:
      - C++ API:
          - C++ Core API: sc-memory/api/cpp/core/api.md
          - C++ Extended API:
              - C++ System identifier API: sc-memory/api/cpp/extended/helper_api.md
              - C++ ScTemplate API: sc-memory/api/cpp/extended/template_api.md
              - C++ Agents API:
                  - C++ Events API: sc-memory/api/cpp/extended/agents/events.md
                  - C++ Event subscriptions API: sc-memory/api/cpp/extended/agents/event_subscriptions.md
                  - C++ Waits API: sc-memory/api/cpp/extended/agents/waits.md
                  - C++ Agents API: sc-memory/api/cpp/extended/agents/agents.md
                  - C++ Keynodes API: sc-memory/api/cpp/extended/agents/keynodes.md
                  - C++ Actions API: sc-memory/api/cpp/extended/agents/actions.md
                  - C++ Agent context API: sc-memory/api/cpp/extended/agents/agent_context.md
                  - C++ Modules API: sc-memory/api/cpp/extended/agents/modules.md
          - C++ Guides:
              - C++ Simple guide for implementing agent: sc-memory/api/cpp/guides/simple_guide_for_implementing_agent.md
      - Python API:
          - Python Core API: https://github.com/ostis-ai/py-sc-client
          - Python Extended API: https://github.com/ostis-ai/py-sc-kpm
      - TypeScript API:
          - TypeScript Core API: https://github.com/ostis-ai/ts-sc-client
      - Sc-element types: scs/sc_element_types.md
      - SCs-code: scs/scs.md
  - Utils:
      - Agents: sc-kpm/kpm.md
  - Tools:
      - Knowledge Base Builder: sc-tools/sc_builder.md
      - Knowledge Base repo file: sc-tools/kb_repo_file.md
      - Websocket Server: sc-tools/sc_server.md
      - Sc-machine Runner: sc-tools/sc_machine.md
  - Development:
      - Contributing Guide: https://github.com/ostis-ai/sc-machine/blob/main/CONTRIBUTING.md
      - Codestyle Guide: dev/codestyle.md
      - Dev Container: dev/devcontainer.md
  - License: license.md
  - Changelog: changelog.md
  - Thirdparty: thirdparty.md

theme: material

markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.details
  - pymdownx.superfences
