site_name: SC-machine

extra_css:
  - _assets/main.css
extra_javascript:
  - _assets/scg.min.js
  - _assets/main.js

pages:
  - Home: index.md
  - Build:
    - Build on Linux: build/linux-build.md
    - Build on Windows: build/windows-build.md
  - Development:
    - Git-workflow: dev/git-workflow.md
    - Pull requets: dev/pr.md
    - Codestyle: dev/codestyle.md
    - Unit tests: dev/test.md
  - API:
    - Meta programming: cpp/cpp-meta.md
    - Agents: cpp/kpm.md
    - Template: cpp/templates.md
    - Common: cpp/common.md
    - Python:
      - Common: python/python.md
      - Library: python/library.md
      - Wrapped classes: python/cpp_wrap.md
  - Common:
    - Element types: cpp/el_types.md
    - Configuration files: other/config.md
    - Sctp-protocol: net/sctp.md
    - SCs language: other/scs.md
  - License: license.md
  - Changelog: changelog.md
  - Thirdparty: thirdparty.md

theme: material

markdown_extensions:
  - markdown_include.include
  - admonition
  - codehilite
  - pymdownx.details
  - pymdownx.superfences
