site_name: SC-machine

extra_css:
  - _assets/main.css
extra_javascript:
  - _assets/scg.min.js
  - _assets/main.js

nav:
  - Home: index.md
  - Build:
    - Build on Linux: build/linux-build.md
    - Build on Windows: build/windows-build.md
    - Build on OSX: build/osx-build.md
    - CMake Flags: build/cmake-flags.md
  - Development:
    - Git-workflow: dev/git-workflow.md
    - Pull requets: dev/pr.md
    - Codestyle: dev/codestyle.md
  - Common:
    - Element types: cpp/el_types.md
    - Configuration files: other/config.md
    - Sctp-protocol: net/sctp.md
    - SCs language: other/scs.md
  - API:
    - Meta programming: cpp/cpp-meta.md
    - Agents: cpp/kpm.md
    - Template: cpp/templates.md
    - Common: cpp/common.md
    - Python:
      - Common: python/python.md
      - Library: python/library.md
      - Wrapped classes: python/cpp_wrap.md
  - Http:
      - Common: http/index.md
      - WebSocket: http/websocket.md
  - Tools:
      - Builder: tools/kb_builder.md
  - License: license.md
  - Changelog: changelog.md
  - Thirdparty: thirdparty.md

theme: material

markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.details
  - pymdownx.superfences
